"""Explanation and confirmation flow (FR-3.1 .. FR-3.6).

The explanation is generated by the LLM (via the pluggable `Explainer`
protocol) but explanation generation and gate enforcement are separate code
paths: nothing the LLM returns can alter the tier or skip confirmation
(FR-3.2). This module owns the actual gating decision.
"""

from __future__ import annotations

import secrets
import string
from dataclasses import dataclass
from typing import Callable, Protocol

from .classifier import ClassificationResult
from .tiers import Tier


class Explainer(Protocol):
    def explain(self, result: ClassificationResult) -> str:
        ...


class StaticExplainer:
    """Fallback explainer used when no LLM is configured. Deterministic and
    offline; real deployments should inject an LLM-backed Explainer."""

    def explain(self, result: ClassificationResult) -> str:
        lines = [
            f"Command/tool: {result.raw}",
            f"Tier: {result.tier.name} ({result.tier.label})",
            f"Matched rule: {result.matched_rule}",
        ]
        if result.explanation_seed:
            lines.append(f"Why: {result.explanation_seed}")
        if result.sub_commands:
            lines.append("Decomposed sub-commands: " + "; ".join(result.sub_commands))
        return "\n".join(lines)


@dataclass
class GateDecision:
    approved: bool
    reason: str


def _generate_confirmation_phrase() -> str:
    """A short, hard-to-fat-finger phrase for T4/T5 typed confirmation."""
    alphabet = string.ascii_uppercase + string.digits
    token = "".join(secrets.choice(alphabet) for _ in range(6))
    return f"CONFIRM-{token}"


class ConfirmationGate:
    """Enforces the y/n vs typed-phrase vs deny-by-default policy.

    `prompt_fn` and `input_fn` are injected so this can be unit tested and
    swapped for a non-interactive UI later.
    """

    def __init__(
        self,
        explainer: Explainer | None = None,
        *,
        allow_tier5: bool = False,
        print_fn: Callable[[str], None] = print,
        input_fn: Callable[[str], str] = input,
    ) -> None:
        self.explainer = explainer or StaticExplainer()
        self.allow_tier5 = allow_tier5
        self._print = print_fn
        self._input = input_fn

    def decide(self, result: ClassificationResult) -> GateDecision:
        tier = result.tier

        if not tier.requires_confirmation:
            # T1/T2: auto-approve, log only (FR handled by caller).
            return GateDecision(True, "auto-approved: below confirmation threshold")

        if tier.denied_by_default and not self.allow_tier5:
            return GateDecision(
                False,
                "denied by default: Tier 5 requires launching with --allow-tier5",
            )

        explanation = self.explainer.explain(result)
        self._print(explanation)

        if tier.requires_typed_phrase:
            phrase = _generate_confirmation_phrase()
            self._print(
                f"This is a {tier.name} action. Type the phrase exactly to proceed: {phrase}"
            )
            typed = self._input("> ")
            if typed.strip() == phrase:
                return GateDecision(True, "approved: typed confirmation phrase matched")
            return GateDecision(False, "denied: typed confirmation phrase did not match")

        # T3: simple y/n
        answer = self._input("Proceed? [y/N] > ").strip().lower()
        if answer in ("y", "yes"):
            return GateDecision(True, "approved: y/n confirmation")
        return GateDecision(False, "denied: y/n confirmation declined")
